### ISSUE TITLE
n_adj+n_mtr accidentally commented out?

### ISSUE THREAD

**Issue by goodmami** [delph-in/JaEn#1]
In `shared/mtr.tdl` I see that the `n_adj+n_mtr` type was commented out in a commit: https://github.com/delph-in/JaEn/commit/f094327b32381e10124e700d0606ab003d44a5a7#diff-7e0c510906e928b7e15dfa5cc54ba881R2049

The type name is duplicated in `jaen/mtr.tdl` with an identical definition, so I think JaEn grammars were able to compile with that version, but if it's meant to be commented out I think the whole definition should be commented out. If not, why is it duplicated in `jaen/mtr.tdl`?

**Comment by fcbond** [comment]
I am not sure, but I think they were different, and then became the same.   I think the one in shared should be uncommented, and the one in jaen removed.
